const shoes = {
    shoe1: {
        name: "pink-shoes",
        image: "/images/a-1.png",
        brand: "adidas",
        price: 3400,
        status: "available",
        color: 'pink',
    },
    shoe2: {
        name: "superstar",
        image: "/images/a-2.png",
        brand: "adidas",
        price: 5600,
        status: "available",
        color: 'white',
    },
    shoe3: {
        name: "trendy-sneakers",
        image: "/images/h-1.png",
        brand: "h&m",
        price: 2500,
        status: "unavailable",
        color: 'pink',
    },
    shoe4: {
        name: "trainers",
        image: "/images/h-2.jpg",
        brand: "h&m",
        price: 3000,
        status: "available",
        color: "yellow",
    },
    shoe5: {
        name: "zoomx-shoes",
        image: "/images/n-1.jpeg",
        brand: "nike",
        price: 4500,
        status: "unavailable",
        color: "blue",
    },
    shoe6: {
        name: "black-trainers",
        image: "/images/n-2.jpeg",
        brand: "nike",
        price: 6700,
        status: "available",
        color: "black",
    },
    shoe7: {
        name: "blue-shoes",
        image: "/images/n-3.jpeg",
        brand: "nike",
        price: 3500,
        status: "available",
        color: "blue",
    },
    shoe8: {
        name: "b-w",
        image: "/images/p-1.jpeg",
        brand: "puma",
        price: 5500,
        status: "available",
        color: "black",
    },
    shoe9: {
        name: "strap-shoes",
        image: "/images/p-2.jpeg",
        brand: "puma",
        price: 4500,
        status: "available",
        color: "black",
    },
    shoe10: {
        name: "pink-sneakers",
        image: "/images/p-3.jpeg",
        brand: "puma",
        price: 7600,
        status: "available",
        color: "pink",
    },
};

export default shoes;